### ISSUE TITLE
Repo sync is not syncing

### ISSUE THREAD

**Issue by Ratatouilledummie** [halogenOS/android_manifest#18] opened 2022-09-08 14:44 UTC
repo sync -j4 -c --no-tags --no-clone-bundle -f build/make external/xos vendor/halogenOS

**Comment by Ratatouilledummie** [comment] 2022-09-08 14:45
error: project build/make not found

**Comment by xdevs23** [comment] 2022-09-10 21:22
Was about to say the same thing.

**Comment by xdevs23** [comment] 2022-09-10 21:23
Closing because there is no issue

**Comment by windowz414** [comment] 2022-09-10 23:03
Thanks to @shizukachanwa, I can confirm this occurs in XOS-12.1 branch. I'll try to fix this and close this issue once done.

**Comment by windowz414** [comment] 2022-09-10 23:16
That error is your mistake for initializing in your home folder somehow. Avoid doing so. It will not only break repo tool but also cause breakages on the Android build system as well.

```
rm -rf ~/.repo
mkdir ~/xossrc
cd ~/xossrc
```

**Closed as not planned by windowz414** 2022-09-10 23:16 UTC
Labels: invalid

**Comment by xdevs23** [comment] 2022-09-11 19:37
I tested syncing today and it worked fine. Yes, doing this in your home directory is not only discouraged but also a danger to your data. The instructions mention creating a directory and running the init command inside of it.
